# Generated by Django 3.1.7 on 2021-03-11 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('May_we_contact_you', models.BooleanField(default=False)),
                ('May_we_contact_you_with', models.CharField(max_length=200)),
            ],
        ),
    ]
