# Generated by Django 3.1.7 on 2021-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
