# Generated by Django 3.1.7 on 2021-03-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0010_cartproduct_go_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='go_order',
        ),
        migrations.AddField(
            model_name='cart',
            name='go_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shapp.order'),
        ),
    ]
