# Generated by Django 3.1.7 on 2021-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0015_auto_20210313_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book_rent_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
