# Generated by Django 3.1.7 on 2021-03-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0017_auto_20210328_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_dates',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 37, 18, 809471)),
        ),
    ]
