# Generated by Django 3.1.7 on 2021-03-31 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0019_auto_20210328_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 11, 33, 36, 650738)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_dates',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 11, 33, 36, 650008)),
        ),
        migrations.AlterField(
            model_name='sendmailrent',
            name='created_dates',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 11, 33, 36, 651313)),
        ),
    ]
